### ISSUE TITLE
Daemon unable to create mount source path

### ISSUE THREAD

**Issue by KimPrince** [EscolaLMS/Create-LMS-App#40]
While installing on mac (with intel chip) I received the following error:

```
Error response from daemon: error while creating mount source path '/Users/my_home_dir/code/EscolaLMS/docker/postgres-data': mkdir /Users/my_home_dir/code/EscolaLMS/docker: operation not permitted
make: *** [docker-up] Error 1
```
The installation command, as follows, was executed with sudo:

`sudo npx --package=@escolalms/cla lms`

**Comment by qunabu** [comment]
@KimPrince can you give me a context
- what system your using 
- what docker version you have 
- any other helpfull system information

**Comment by qunabu** [comment]
@KimPrince can you try again without `sudo`

**Comment by KimPrince** [comment]
Thanks, I tried again without sudo and it worked fine.
The api doc link, http://api.wellms.localhost/api/documentation, is returning a 404.  I'll raise a separate issue for this.
