### ISSUE TITLE
API Doc returning a 404

### ISSUE THREAD

**Issue by KimPrince** [EscolaLMS/Create-LMS-App#41]
After installation, at the api doc URL, http://api.wellms.localhost/api/documentation, nginx returns a 404.

**Comment by DuyCP** [comment]
I encountered the same issue

**Comment by qunabu** [comment]
Can you confirm its not working right now - ale raise another issue 
![image](https://github.com/EscolaLMS/Create-LMS-App/assets/214608/a1ce74cc-8ec6-48e8-8129-6324e3a132ce)
