### ISSUE TITLE
add command to init.sh checking if deps are installed

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Create-LMS-App#8]
* node.js
* docker 
* docker-composer

must be installed this must be checked in init.sh 

https://stackoverflow.com/questions/592620/how-can-i-check-if-a-program-exists-from-a-bash-script

**Comment by KrzysztofDziedziechEscolasoft** [comment]
on linux 
before run ./init.sh 
run `sed -i -e 's/\r$//' init.sh`

**Comment by KrzysztofDziedziechEscolasoft** [comment]
- u przemka admin i front instalują sie noramlnie (ja mam coś nie tak z konfiguracją na WSL)
- osobno postawione api u nie przechodzi normalnie, natomiast podczas odpalania tego pojawia sie błąd podczas stawiania dockera (jeden kontener nie chce się uruchomić - wina WSL chyba) - ale u Pawła działa to poprawnie (ma Mac'ka)

podsumowując przydał by mi się mac :P
